package com.example.demo.db.domain;

public class SkyArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sky_area.areaId
     *
     * @mbggenerated
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sky_area.areaName
     *
     * @mbggenerated
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sky_area.addTime
     *
     * @mbggenerated
     */
    private Long addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sky_area.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sky_area.areaId
     *
     * @return the value of sky_area.areaId
     *
     * @mbggenerated
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sky_area.areaId
     *
     * @param areaid the value for sky_area.areaId
     *
     * @mbggenerated
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sky_area.areaName
     *
     * @return the value of sky_area.areaName
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sky_area.areaName
     *
     * @param areaname the value for sky_area.areaName
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sky_area.addTime
     *
     * @return the value of sky_area.addTime
     *
     * @mbggenerated
     */
    public Long getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sky_area.addTime
     *
     * @param addtime the value for sky_area.addTime
     *
     * @mbggenerated
     */
    public void setAddtime(Long addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sky_area.status
     *
     * @return the value of sky_area.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sky_area.status
     *
     * @param status the value for sky_area.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}